version: '2.0'
services:
  coze-on-wechat:
    image: registry.nextv.show/baizeai/coze-on-wechat
    container_name: coze-on-wechat
    security_opt:
      - seccomp:unconfined
    volumes:
      # Mount the storage directory to the container, for storing user files.
      - ./config.json:/app/config.json
      - ./plugins:/app/plugins:rw,z