version: '2.0'
services:
  coze-on-wechat:
    image: registry.nextv.show/baizeai/coze-on-wechat
    container_name: coze-on-wechat
    security_opt:
      - seccomp:unconfined
    environment:
      CHANNEL_TYPE: 'wx'
      MODEL: 'coze'
      COZE_API_BASSE: https://api.coze.cn/open_api/v2'
      COZE_API_KEY: 'pat_enpRlfXCEWApMN5Q4B6DuUv3RX4y6Ve0JlzwQy0tQkDl3zjAN6iuAQHeqnXWkjLk'
      COZE_BOT_ID: '7402151418448543744'
      PROXY: ''
      HOT_RELOAD: 'false'
      SINGLE_CHAT_PREFIX: '["bot", "@bot"]'
      SINGLE_CHAT_REPLY_PREFIX: '"[bot] "'
      GROUP_CHAT_PREFIX: '["@bot"]'
      GROUP_NAME_WHITE_LIST: '["ChatGPT测试群", "ChatGPT测试群2"]'
      IMAGE_CREATE_PREFIX: '["画", "看", "找"]'
      CONVERSATION_MAX_TOKENS: 2500
      SPEECH_RECOGNITION: 'False'
      CHARACTER_DESC: '你是基于大语言模型的AI智能助手，旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。'
      EXPIRES_IN_SECONDS: 3600
      subscribe_msg: '感谢您的关注！\n这里是AI智能助手，可以自由对话。\n支持语音对话。\n支持图片输入。\n支持图片输出，画字开头的消息将按要求创作图片。\n支持tool、角色扮演和文字冒险等丰富的插件。\n输入{trigger_prefix}#help 查看详细指令。'
      USE_GLOBAL_PLUGIN_CONFIG: 'True'
      USE_LINKAI: 'False'
      LINKAI_API_KEY: ''
      LINKAI_APP_CODE: ''
